name: Test then Deploy Server

on:
  push:
    branches: [master]
    paths: 'server/**'
  pull_request:
    branches: [master]
    paths: 'server/**'

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --if-present
        working-directory: ./server
      - run: npm run build --if-present
        working-directory: ./server
      - run: npm run test --if-present
        working-directory: ./server

  Deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: ${{ secrets.GCP_BE_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_BE_SA_KEY }}
        project_id: ${{ secrets.BE_PROJECT_ID }}

    - name: Publish app to Google App Engine
      run: |
        gcloud auth activate-service-account ${{ secrets.GCP_BE_SA_EMAIL }} --key-file=client-secret.json
        gcloud config set project ${{ secrets.BE_PROJECT_ID }}
        gcloud -q app deploy ./server/app.yaml --promote
        